In [1]:
import pandas as pd

data = {
    'Email': ['kim@gmail.com', 'lee@naver.com', 'park@daum.net', 'choi@gmail.com'],
    'Name': ['Kim', 'Lee', 'Park', 'Choi'],
    'Comment': ['Hello!!', 'Nice to meet you :)', '  Thanks!! ', 'ok~~~']
}

df = pd.DataFrame(data)
df

            Email  Name              Comment
0   kim@gmail.com   Kim              Hello!!
1   lee@naver.com   Lee  Nice to meet you :)
2   park@daum.net  Park            Thanks!!
3  choi@gmail.com  Choi                ok~~~

## 문자열 처리
- 문자열은 텍스트 데이터를 다루기 위한 단위
- 텍스트 컬럼의 정제, 분류, 검색 등의 전처리 과정에서 문자열 처리 함수가 자주 사용

| 주요 함수 | 설명 |
| ------- | -- |
| `str.lower()` | 문자열을 소문자/대문자로 변환 |
| `str.strip()`, `str.lstrip()`, `str.rstrip()` | 문자열 양쪽 또는 한족 공백 제거 |
| `str.replace(old, new)` | 특정 문자 또는 문자열 치환 |
| `str.contains('패턴')` | 특정 패턴이 포함된 경우 True 반환(불리언 필터링 활용) |
| `str.split('구분자')`  | 구분자를 기준으로 문자열 분리(리스트 형태 반환) |
| `str[0:5]` | 특정 위치의 문자 추출(슬라이싱) |
| `str.len()` | 문자열 길이 반환 |

In [2]:
df

            Email  Name              Comment
0   kim@gmail.com   Kim              Hello!!
1   lee@naver.com   Lee  Nice to meet you :)
2   park@daum.net  Park            Thanks!!
3  choi@gmail.com  Choi                ok~~~

### 1. 문자열 분리

In [14]:
df['Email'].str.split('@').str[1] #split 함수는 series 형태로 반환

0    gmail.com
1    naver.com
2     daum.net
3    gmail.com
Name: Email, dtype: object

### 2. 소문자 변환

In [15]:
df['Name'].str.lower()

0     kim
1     lee
2    park
3    choi
Name: Name, dtype: object

### 3. 공백제거

In [17]:
df['Comment'].iloc[2]

'  Thanks!! '

In [19]:
df['Comment'].str.strip().iloc[2]

'Thanks!!'

### 4. 특정 문자열 포함 여부

In [21]:
df[df['Email'].str.contains('gmail')]

            Email  Name  Comment
0   kim@gmail.com   Kim  Hello!!
3  choi@gmail.com  Choi    ok~~~

### 5. 문자열 치환

In [22]:
df['Comment'].str.replace('!', '', regex=False) # regex=True시, 정규표현식으로 패턴 인식

0                  Hello
1    Nice to meet you :)
2                Thanks
3                  ok~~~
Name: Comment, dtype: object

### 6. 문자열 슬라이싱

In [23]:
df['Email'].str[:5]

0    kim@g
1    lee@n
2    park@
3    choi@
Name: Email, dtype: object