In [1]:
import pandas as pd

data = {
    'Email': ['kim@gmail.com', 'lee@naver.com', 'park@daum.net', 'choi@gmail.com'],
    'Name': ['Kim', 'Lee', 'Park', 'Choi'],
    'Comment': ['Hello!!', 'Nice to meet you :)', '  Thanks!! ', 'ok~~~']
}

df = pd.DataFrame(data)
df

            Email  Name              Comment
0   kim@gmail.com   Kim              Hello!!
1   lee@naver.com   Lee  Nice to meet you :)
2   park@daum.net  Park            Thanks!!
3  choi@gmail.com  Choi                ok~~~

## 문자열 처리
- 문자열은 텍스트 데이터를 다루기 위한 단위
- 텍스트 컬럼의 정제, 분류, 검색 등의 전처리 과정에서 문자열 처리 함수가 자주 사용

| 주요 함수 | 설명 |
| ------- | -- |
| `str.lower()` | 문자열을 소문자/대문자로 변환 |
| `str.strip()`, `str.lstrip()`, `str.rstrip()` | 문자열 양쪽 또는 한족 공백 제거 |
| `str.replace(old, new)` | 특정 문자 또는 문자열 치환 |
| `str.contains('패턴')` | 특정 패턴이 포함된 경우 True 반환(불리언 필터링 활용) |
| `str.split('구분자')`  | 구분자를 기준으로 문자열 분리(리스트 형태 반환) |
| `str[0:5]` | 특정 위치의 문자 추출(슬라이싱) |
| `str.len()` | 문자열 길이 반환 |

In [2]:
df

            Email  Name              Comment
0   kim@gmail.com   Kim              Hello!!
1   lee@naver.com   Lee  Nice to meet you :)
2   park@daum.net  Park            Thanks!!
3  choi@gmail.com  Choi                ok~~~

### 1. 문자열 분리

In [14]:
df['Email'].str.split('@').str[1] #split 함수는 series 형태로 반환

0    gmail.com
1    naver.com
2     daum.net
3    gmail.com
Name: Email, dtype: object

### 2. 소문자 변환

In [15]:
df['Name'].str.lower()

0     kim
1     lee
2    park
3    choi
Name: Name, dtype: object

### 3. 공백제거

In [17]:
df['Comment'].iloc[2]

'  Thanks!! '

In [19]:
df['Comment'].str.strip().iloc[2]

'Thanks!!'

### 4. 특정 문자열 포함 여부

In [21]:
df[df['Email'].str.contains('gmail')]

            Email  Name  Comment
0   kim@gmail.com   Kim  Hello!!
3  choi@gmail.com  Choi    ok~~~

### 5. 문자열 치환

In [22]:
df['Comment'].str.replace('!', '', regex=False) # regex=True시, 정규표현식으로 패턴 인식

0                  Hello
1    Nice to meet you :)
2                Thanks
3                  ok~~~
Name: Comment, dtype: object

### 6. 문자열 슬라이싱

In [23]:
df['Email'].str[:5]

0    kim@g
1    lee@n
2    park@
3    choi@
Name: Email, dtype: object

In [30]:
# 실제 쓸 수 있는 함수만 깔끔하게 보기
print([method for method in dir(df['Email'].str) if not method.startswith('_')])

['capitalize', 'casefold', 'cat', 'center', 'contains', 'count', 'decode', 'encode', 'endswith', 'extract', 'extractall', 'find', 'findall', 'fullmatch', 'get', 'get_dummies', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'islower', 'isnumeric', 'isspace', 'istitle', 'isupper', 'join', 'len', 'ljust', 'lower', 'lstrip', 'match', 'normalize', 'pad', 'partition', 'removeprefix', 'removesuffix', 'repeat', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'slice', 'slice_replace', 'split', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'wrap', 'zfill']

In [31]:
help(df['Email'].str.split)

Help on method split in module pandas.core.strings.accessor:

split(pat: 'str | re.Pattern | None' = None, *, n=-1, expand: 'bool' = False, regex: 'bool | None' = None) method of pandas.core.strings.accessor.StringMethods instance
    Split strings around given separator/delimiter.

    Splits the string in the Series/Index from the beginning,
    at the specified delimiter string.

    Parameters
    ----------
    pat : str or compiled regex, optional
        String or regular expression to split on.
        If not specified, split on whitespace.
    n : int, default -1 (all)
        Limit number of splits in output.
        ``None``, 0 and -1 will be interpreted as return all splits.
    expand : bool, default False
        Expand the split strings into separate columns.

        - If ``True``, return DataFrame/MultiIndex expanding dimensionality.
        - If ``False``, return Series/Index, containing lists of strings.

    regex : bool, default None
        Determines if the passed-in pattern is a regular expression:

        - If ``True``, assumes the passed-in pattern is a regular expression
        - If ``False``, treats the pattern as a literal string.
        - If ``None`` and `pat` length is 1, treats `pat` as a literal string.
        - If ``None`` and `pat` length is not 1, treats `pat` as a regular expression.
        - Cannot be set to False if `pat` is a compiled regex

        .. versionadded:: 1.4.0

    Returns
    -------
    Series, Index, DataFrame or MultiIndex
        Type matches caller unless ``expand=True`` (see Notes).

                      Raises
                      ------
                      ValueError
                          * if `regex` is False and `pat` is a compiled regex

    See Also
    --------
    Series.str.split : Split strings around given separator/delimiter.
    Series.str.rsplit : Splits string around given separator/delimiter,
        starting from the right.
    Series.str.join : Join lists contained as elements in the Series/Index
        with passed delimiter.
    str.split : Standard library version for split.
    str.rsplit : Standard library version for rsplit.

    Notes
    -----
    The handling of the `n` keyword depends on the number of found splits:

    - If found splits > `n`,  make first `n` splits only
    - If found splits <= `n`, make all splits
    - If for a certain row the number of found splits < `n`,
      append `None` for padding up to `n` if ``expand=True``

    If using ``expand=True``, Series and Index callers return DataFrame and
    MultiIndex objects, respectively.

    Use of `regex =False` with a `pat` as a compiled regex will raise an error.

    Examples
    --------
    >>> s = pd.Series(
    ...     [
    ...         "this is a regular sentence",
    ...         "https://docs.python.org/3/tutorial/index.html",
    ...         np.nan
    ...     ]
    ... )
    >>> s
    0                       this is a regular sentence
    1    https://docs.python.org/3/tutorial/index.html
    2                                              NaN
    dtype: object

    In the default setting, the string is split by whitespace.

    >>> s.str.split()
    0                   [this, is, a, regular, sentence]
    1    [https://docs.python.org/3/tutorial/index.html]
    2                                                NaN
    dtype: object

    Without the `n` parameter, the outputs of `rsplit` and `split`
    are identical.

    >>> s.str.rsplit()
    0                   [this, is, a, regular, sentence]
    1    [https://docs.python.org/3/tutorial/index.html]
    2                                                NaN
    dtype: object

    The `n` parameter can be used to limit the number of splits on the
    delimiter. The outputs of `split` and `rsplit` are different.

    >>> s.str.split(n=2)
    0                     [this, is, a regular sentence]
    1    [https://docs.python.org/3/tutorial/index.html]
    2                                                NaN
    dtype: object

    >>> s.str.rsplit(n=2)
    0                     [this is a, regular, sentence]
    1    [https://docs.python.org/3/tutorial/index.html]
    2                                                NaN
    dtype: object

    The `pat` parameter can be used to split by other characters.

    >>> s.str.split(pat="/")
    0                         [this is a regular sentence]
    1    [https:, , docs.python.org, 3, tutorial, index...
    2                                                  NaN
    dtype: object

    When using ``expand=True``, the split elements will expand out into
    separate columns. If NaN is present, it is propagated throughout
    the columns during the split.

    >>> s.str.split(expand=True)
                                                   0     1     2        3         4
    0                                           this    is     a  regular  sentence
    1  https://docs.python.org/3/tutorial/index.html  None  None     None      None
    2                                            NaN   NaN   NaN      NaN       NaN

    For slightly more complex use cases like splitting the html document name
    from a url, a combination of parameter settings can be used.

    >>> s.str.rsplit("/", n=1, expand=True)
                                        0           1
    0          this is a regular sentence        None
    1  https://docs.python.org/3/tutorial  index.html
    2                                 NaN         NaN

    Remember to escape special characters when explicitly using regular expressions.

    >>> s = pd.Series(["foo and bar plus baz"])
    >>> s.str.split(r"and|plus", expand=True)
        0   1   2
    0 foo bar baz

    Regular expressions can be used to handle urls or file names.
    When `pat` is a string and ``regex=None`` (the default), the given `pat` is compiled
    as a regex only if ``len(pat) != 1``.

    >>> s = pd.Series(['foojpgbar.jpg'])
    >>> s.str.split(r".", expand=True)
               0    1
    0  foojpgbar  jpg

    >>> s.str.split(r"\.jpg", expand=True)
               0 1
    0  foojpgbar

    When ``regex=True``, `pat` is interpreted as a regex

    >>> s.str.split(r"\.jpg", regex=True, expand=True)
               0 1
    0  foojpgbar

    A compiled regex can be passed as `pat`

    >>> import re
    >>> s.str.split(re.compile(r"\.jpg"), expand=True)
               0 1
    0  foojpgbar

    When ``regex=False``, `pat` is interpreted as the string itself

    >>> s.str.split(r"\.jpg", regex=False, expand=True)
                   0
    0  foojpgbar.jpg